export const screens = {
    MAIN: 'MAIN',
    HELLO: 'HELLO',
    STARTED: 'STARTED',
    SIGNINSOCIAL: 'SIGNINSOCIAL',
    SIGNUP: 'SIGNUP',
    CHOOSE_INTEREST: 'CHOOSEINTEREST',
    FILL_PROFILE: 'FILLPROFILE',
    APPEARANCE: 'APPEARANCE',
    FORGOT_PASSWORD: 'FORGOTPASSWORD',
}